[project]
name = "tictactoe"
version = "0.3.0"
requires-python = ">=3.9"
dependencies = ["pydantic"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["black", "pylint", "pytest"]

